#%RAML 1.0 ResourceType

description: Collection of available <<resourcePathName>> in the cart.

uses:
  defaultResponses: !include ../libraries/responseBase.raml
  error-types: !include ../types/error-types.raml

get:
  is: [defaultResponses.general: { parentType: <<parentType>> }]
  description: retrieves the list of <<resourcePathName>>
  headers:
    If-None-Match:
      type: string
      description: the unique Etag provided by a potential previous GET
  responses:
    200:
    304:
    404:
    500:
    503:

delete:
  is: [defaultResponses.general: { parentType: <<parentType>> }]
  description: Removes all <<resourcePathName>> in this collection
  responses:
    200:
    204:
    404:
    500:
    503:
    504:  

post:
  is: [defaultResponses.general: { parentType: <<parentType>> }]
  description: |
    Create a new <<resourcePathName|!singularize>> to manage.
  body:
    application/json:
  responses:
    201:
    404:
    500:
    503:
    504:
